unit multiphysics_component_library;
{$mode objfpc}{$H+}
interface
uses multiphysics_graph;
function NewPowerSupply(const ID:string;Voltage,MaxCurrent:Double):TSimComponent;
function NewPWMDriver(const ID:string):TSimComponent;
function NewDCMotor(const ID:string):TSimComponent;
function NewAxisLoad(const ID:string):TSimComponent;
function NewSpeedSensor(const ID:string):TSimComponent;
function NewController(const ID:string):TSimComponent;
function NewResistor(const ID:string;Ohms:Double):TSimComponent;
function NewCapacitor(const ID:string;Farads:Double):TSimComponent;
function NewInductor(const ID:string;Henries:Double):TSimComponent;
function NewRelay(const ID:string):TSimComponent;
function NewStepper(const ID:string):TSimComponent;
function NewServo(const ID:string):TSimComponent;
function NewBLDC(const ID:string):TSimComponent;
function NewGear(const ID:string;Ratio:Double):TSimComponent;
function NewLeadScrew(const ID:string;PitchMM:Double):TSimComponent;
function NewEndStop(const ID:string):TSimComponent;
function NewLED(const ID:string;Vf:Double):TSimComponent;
function NewZener(const ID:string;Vz:Double):TSimComponent;
function NewBJT(const ID:string;PNP:Boolean):TSimComponent;
function NewSwitch(const ID:string):TSimComponent;
function NewPotentiometer(const ID:string;Ohms:Double):TSimComponent;
function NewFuse(const ID:string;Amps:Double):TSimComponent;
function NewBattery(const ID:string;Volts,Ah:Double):TSimComponent;
function NewACSource(const ID:string;Vrms,Hz:Double):TSimComponent;
function NewTransformer(const ID:string;Ratio:Double):TSimComponent;
function NewLDO(const ID:string;Vout:Double):TSimComponent;
function NewOpAmp(const ID:string):TSimComponent;
function NewLogic(const ID:string;Kind:TComponentKind):TSimComponent;
function NewTimer555(const ID:string):TSimComponent;
function NewADC(const ID:string;Bits:Integer):TSimComponent;
function NewDAC(const ID:string;Bits:Integer):TSimComponent;
function NewOptocoupler(const ID:string):TSimComponent;
function NewBuck(const ID:string):TSimComponent;
function NewBoost(const ID:string):TSimComponent;
function NewHBridge(const ID:string):TSimComponent;
function NewStepperDriver(const ID:string):TSimComponent;
function NewSCR(const ID:string):TSimComponent;
function NewTRIAC(const ID:string):TSimComponent;
function NewIGBT(const ID:string):TSimComponent;
function NewMCU(const ID:string;Kind:TComponentKind;GPIO,ADC,PWM:Integer):TSimComponent;
function NewATmega328P(const ID:string):TSimComponent;
function NewESP32(const ID:string):TSimComponent;
function NewRP2040(const ID:string):TSimComponent;
function NewSTM32(const ID:string):TSimComponent;
function NewMemory(const ID:string;Kind:TComponentKind;Bytes:Integer):TSimComponent;
function NewClock(const ID:string;Hz:Double):TSimComponent;
implementation
function NewPowerSupply(const ID:string;Voltage,MaxCurrent:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Fonte',ckPowerSupply,cdElectrical);Result.AddPort('V+',ptElectrical);Result.AddPort('GND',ptElectrical);Result.Parameters.Values['voltage']:=FloatToStr(Voltage);Result.Parameters.Values['max_current']:=FloatToStr(MaxCurrent);end;
function NewPWMDriver(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Driver PWM',ckPWMDriver,cdElectronic);Result.AddPort('VIN',ptElectrical);Result.AddPort('VOUT',ptElectrical);Result.AddPort('CMD',ptSignal);end;
function NewDCMotor(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Motor DC',ckDCMotor,cdElectrical);Result.AddPort('PWR',ptElectrical);Result.AddPort('SHAFT',ptMechanicalRotary);Result.AddPort('TEMP',ptThermal);end;
function NewAxisLoad(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Carga de eixo',ckAxisLoad,cdMechanical);Result.AddPort('SHAFT',ptMechanicalRotary);end;
function NewSpeedSensor(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Sensor velocidade',ckSpeedSensor,cdSensor);Result.AddPort('SHAFT',ptMechanicalRotary);Result.AddPort('OUT',ptSignal);end;
function NewController(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Controlador',ckController,cdController);Result.AddPort('SENSOR',ptSignal);Result.AddPort('PWM',ptSignal);end;
function NewResistor(const ID:string;Ohms:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Resistor',ckResistor,cdElectrical);Result.AddPort('A',ptElectrical);Result.AddPort('B',ptElectrical);Result.Parameters.Values['resistance']:=FloatToStr(Ohms);end;
function NewCapacitor(const ID:string;Farads:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Capacitor',ckCapacitor,cdElectrical);Result.AddPort('A',ptElectrical);Result.AddPort('B',ptElectrical);Result.Parameters.Values['capacitance']:=FloatToStr(Farads);end;
function NewInductor(const ID:string;Henries:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Indutor',ckInductor,cdElectrical);Result.AddPort('A',ptElectrical);Result.AddPort('B',ptElectrical);Result.Parameters.Values['inductance']:=FloatToStr(Henries);end;
function NewRelay(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Rele',ckRelay,cdElectronic);Result.AddPort('COIL+',ptElectrical);Result.AddPort('COIL-',ptElectrical);Result.AddPort('COM',ptElectrical);Result.AddPort('NO',ptElectrical);Result.AddPort('NC',ptElectrical);end;
function NewStepper(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Motor de passo',ckStepperMotor,cdElectrical);Result.AddPort('PWR',ptElectrical);Result.AddPort('STEP',ptSignal);Result.AddPort('DIR',ptSignal);Result.AddPort('SHAFT',ptMechanicalRotary);end;
function NewServo(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Servo',ckServoMotor,cdElectrical);Result.AddPort('PWR',ptElectrical);Result.AddPort('CMD',ptSignal);Result.AddPort('SHAFT',ptMechanicalRotary);end;
function NewBLDC(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Motor BLDC',ckBLDCMotor,cdElectrical);Result.AddPort('PWR',ptElectrical);Result.AddPort('CMD',ptSignal);Result.AddPort('SHAFT',ptMechanicalRotary);end;
function NewGear(const ID:string;Ratio:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Engrenagem',ckGear,cdMechanical);Result.AddPort('IN',ptMechanicalRotary);Result.AddPort('OUT',ptMechanicalRotary);Result.Parameters.Values['ratio']:=FloatToStr(Ratio);end;
function NewLeadScrew(const ID:string;PitchMM:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Fuso',ckLeadScrew,cdMechanical);Result.AddPort('SHAFT',ptMechanicalRotary);Result.AddPort('LINEAR',ptMechanicalRotary);Result.Parameters.Values['pitch_mm']:=FloatToStr(PitchMM);end;
function NewEndStop(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Fim de curso',ckEndStop,cdSensor);Result.AddPort('OUT',ptSignal);Result.Parameters.Values['position']:=FloatToStr(0);end;
function NewLED(const ID:string;Vf:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'LED',ckLED,cdElectronic);Result.AddPort('A',ptElectrical);Result.AddPort('K',ptElectrical);Result.Parameters.Values['vf']:=FloatToStr(Vf);end;
function NewZener(const ID:string;Vz:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Zener',ckZener,cdElectronic);Result.AddPort('A',ptElectrical);Result.AddPort('K',ptElectrical);Result.Parameters.Values['vz']:=FloatToStr(Vz);end;
function NewBJT(const ID:string;PNP:Boolean):TSimComponent;begin if PNP then Result:=TSimComponent.Create(ID,'BJT PNP',ckBJT_PNP,cdElectronic)else Result:=TSimComponent.Create(ID,'BJT NPN',ckBJT_NPN,cdElectronic);Result.AddPort('B',ptElectrical);Result.AddPort('C',ptElectrical);Result.AddPort('E',ptElectrical);Result.Parameters.Values['beta']:='100';Result.Parameters.Values['vbe']:='0.7';end;
function NewSwitch(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Chave',ckSwitch,cdElectrical);Result.AddPort('A',ptElectrical);Result.AddPort('B',ptElectrical);Result.Parameters.Values['closed']:='0';end;
function NewPotentiometer(const ID:string;Ohms:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Potenciometro',ckPotentiometer,cdElectrical);Result.AddPort('A',ptElectrical);Result.AddPort('W',ptElectrical);Result.AddPort('B',ptElectrical);Result.Parameters.Values['resistance']:=FloatToStr(Ohms);Result.Parameters.Values['position']:='0.5';end;
function NewFuse(const ID:string;Amps:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Fusivel',ckFuse,cdElectrical);Result.AddPort('A',ptElectrical);Result.AddPort('B',ptElectrical);Result.Parameters.Values['rated_current']:=FloatToStr(Amps);end;
function NewBattery(const ID:string;Volts,Ah:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Bateria',ckBattery,cdElectrical);Result.AddPort('V+',ptElectrical);Result.AddPort('GND',ptElectrical);Result.Parameters.Values['voltage']:=FloatToStr(Volts);Result.Parameters.Values['capacity_ah']:=FloatToStr(Ah);end;
function NewACSource(const ID:string;Vrms,Hz:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Fonte AC',ckACSource,cdElectrical);Result.AddPort('L',ptElectrical);Result.AddPort('N',ptElectrical);Result.Parameters.Values['vrms']:=FloatToStr(Vrms);Result.Parameters.Values['frequency']:=FloatToStr(Hz);end;
function NewTransformer(const ID:string;Ratio:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Transformador',ckTransformer,cdElectrical);Result.AddPort('P1',ptElectrical);Result.AddPort('P2',ptElectrical);Result.AddPort('S1',ptElectrical);Result.AddPort('S2',ptElectrical);Result.Parameters.Values['ratio']:=FloatToStr(Ratio);end;
function NewLDO(const ID:string;Vout:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Regulador LDO',ckLDO,cdElectronic);Result.AddPort('IN',ptElectrical);Result.AddPort('GND',ptElectrical);Result.AddPort('OUT',ptElectrical);Result.Parameters.Values['vout']:=FloatToStr(Vout);end;
function NewOpAmp(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Amplificador operacional',ckOpAmp,cdElectronic);Result.AddPort('V+',ptElectrical);Result.AddPort('V-',ptElectrical);Result.AddPort('IN+',ptElectrical);Result.AddPort('IN-',ptElectrical);Result.AddPort('OUT',ptElectrical);Result.Parameters.Values['gain']:='100000';end;
function NewLogic(const ID:string;Kind:TComponentKind):TSimComponent;begin Result:=TSimComponent.Create(ID,'Porta logica',Kind,cdElectronic);Result.AddPort('A',ptSignal);Result.AddPort('B',ptSignal);Result.AddPort('Y',ptSignal);end;
function NewTimer555(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Timer 555',ckTimer555,cdElectronic);Result.AddPort('VCC',ptElectrical);Result.AddPort('GND',ptElectrical);Result.AddPort('TRIG',ptSignal);Result.AddPort('OUT',ptSignal);end;
function NewADC(const ID:string;Bits:Integer):TSimComponent;begin Result:=TSimComponent.Create(ID,'ADC',ckADC,cdElectronic);Result.AddPort('AIN',ptElectrical);Result.AddPort('DOUT',ptSignal);Result.Parameters.Values['bits']:=IntToStr(Bits);end;
function NewDAC(const ID:string;Bits:Integer):TSimComponent;begin Result:=TSimComponent.Create(ID,'DAC',ckDAC,cdElectronic);Result.AddPort('DIN',ptSignal);Result.AddPort('AOUT',ptElectrical);Result.Parameters.Values['bits']:=IntToStr(Bits);end;
function NewOptocoupler(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Optoacoplador',ckOptocoupler,cdElectronic);Result.AddPort('IN+',ptElectrical);Result.AddPort('IN-',ptElectrical);Result.AddPort('C',ptElectrical);Result.AddPort('E',ptElectrical);Result.Parameters.Values['ctr']:='1';end;
function NewBuck(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Buck',ckBuck,cdElectronic);Result.AddPort('VIN',ptElectrical);Result.AddPort('GND',ptElectrical);Result.AddPort('VOUT',ptElectrical);Result.AddPort('PWM',ptSignal);Result.Parameters.Values['efficiency']:='0.9';end;
function NewBoost(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Boost',ckBoost,cdElectronic);Result.AddPort('VIN',ptElectrical);Result.AddPort('GND',ptElectrical);Result.AddPort('VOUT',ptElectrical);Result.AddPort('PWM',ptSignal);Result.Parameters.Values['efficiency']:='0.9';end;
function NewHBridge(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Ponte H',ckHBridge,cdElectronic);Result.AddPort('VIN',ptElectrical);Result.AddPort('OUTA',ptElectrical);Result.AddPort('OUTB',ptElectrical);Result.AddPort('PWM',ptSignal);Result.AddPort('DIR',ptSignal);end;
function NewStepperDriver(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'Driver STEP/DIR',ckStepperDriver,cdElectronic);Result.AddPort('VMOT',ptElectrical);Result.AddPort('GND',ptElectrical);Result.AddPort('STEP',ptSignal);Result.AddPort('DIR',ptSignal);Result.AddPort('ENABLE',ptSignal);Result.AddPort('A+',ptElectrical);Result.AddPort('A-',ptElectrical);Result.AddPort('B+',ptElectrical);Result.AddPort('B-',ptElectrical);Result.Parameters.Values['current_limit']:='2';end;
function NewSCR(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'SCR',ckSCR,cdElectronic);Result.AddPort('A',ptElectrical);Result.AddPort('K',ptElectrical);Result.AddPort('G',ptSignal);end;
function NewTRIAC(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'TRIAC',ckTRIAC,cdElectronic);Result.AddPort('MT1',ptElectrical);Result.AddPort('MT2',ptElectrical);Result.AddPort('G',ptSignal);end;
function NewIGBT(const ID:string):TSimComponent;begin Result:=TSimComponent.Create(ID,'IGBT',ckIGBT,cdElectronic);Result.AddPort('C',ptElectrical);Result.AddPort('E',ptElectrical);Result.AddPort('G',ptSignal);Result.Parameters.Values['threshold']:='5';Result.Parameters.Values['on_resistance']:='0.05';end;
function NewMCU(const ID:string;Kind:TComponentKind;GPIO,ADC,PWM:Integer):TSimComponent;var I:Integer;begin Result:=TSimComponent.Create(ID,'Microcontrolador',Kind,cdController);Result.AddPort('VCC',ptElectrical);Result.AddPort('GND',ptElectrical);Result.AddPort('RESET',ptSignal);for I:=0 to GPIO-1 do Result.AddPort('GPIO'+IntToStr(I),ptSignal);Result.Parameters.Values['gpio']:=IntToStr(GPIO);Result.Parameters.Values['adc']:=IntToStr(ADC);Result.Parameters.Values['pwm']:=IntToStr(PWM);end;
function NewATmega328P(const ID:string):TSimComponent;begin Result:=NewMCU(ID,ckATmega328P,20,6,6);Result.Name:='ATmega328P / Arduino Uno';Result.Parameters.Values['clock_hz']:='16000000';end;
function NewESP32(const ID:string):TSimComponent;begin Result:=NewMCU(ID,ckESP32,40,18,16);Result.Name:='ESP32';Result.Parameters.Values['clock_hz']:='240000000';end;
function NewRP2040(const ID:string):TSimComponent;begin Result:=NewMCU(ID,ckRP2040,30,4,16);Result.Name:='RP2040';Result.Parameters.Values['clock_hz']:='133000000';end;
function NewSTM32(const ID:string):TSimComponent;begin Result:=NewMCU(ID,ckSTM32,37,16,12);Result.Name:='STM32';Result.Parameters.Values['clock_hz']:='72000000';end;
function NewMemory(const ID:string;Kind:TComponentKind;Bytes:Integer):TSimComponent;begin Result:=TSimComponent.Create(ID,'Memoria',Kind,cdElectronic);Result.AddPort('BUS',ptSignal);Result.Parameters.Values['bytes']:=IntToStr(Bytes);end;
function NewClock(const ID:string;Hz:Double):TSimComponent;begin Result:=TSimComponent.Create(ID,'Clock',ckClock,cdElectronic);Result.AddPort('OUT',ptSignal);Result.Parameters.Values['frequency_hz']:=FloatToStr(Hz);end;
end.
