unit multisuite_test_catalog;
{$mode objfpc}{$H+}
interface
uses Classes,SysUtils;
type TTestDefinition=record Tool,Name,Source,Executable:string;end;TTestDefinitions=array of TTestDefinition;
function DefaultTestCatalog:TTestDefinitions;
implementation
procedure Add(var A:TTestDefinitions;const Tool,N,S,E:string);var I:Integer;begin I:=Length(A);SetLength(A,I+1);A[I].Tool:=Tool;A[I].Name:=N;A[I].Source:=S;A[I].Executable:=E;end;
function DefaultTestCatalog:TTestDefinitions;begin SetLength(Result,0);
 Add(Result,'MultiCAM','Interpolacao de nivelamento compartilhada','tests/test_shared_heightmap.lpr','tests/test_shared_heightmap');
 Add(Result,'MultiCAM','Compensacao Z compartilhada','tests/test_shared_zcompensation.lpr','tests/test_shared_zcompensation');
 Add(Result,'MultiCNC','Simulator','tests/test_simulator.lpr','tests/test_simulator');
 Add(Result,'MultiCNC','Controle de fluxo, alarmes e seguranca','tests/test_streaming.lpr','tests/test_streaming');
 Add(Result,'MultiSuite','Numeros com ponto decimal (pt-BR)','tests/test_locale_invariant.lpr','tests/test_locale_invariant');
 Add(Result,'MultiCAD','Nucleo: esboco, operacoes, booleanas, vista, STL/DXF e medir','multicad/tests/test_multicad.lpr','multicad/tests/test_multicad');
 Add(Result,'MultiCAD','Interface: janela, vista 3D, esboco e PropertyManager','multicad/tests/test_multicad_ui.lpr','multicad/tests/test_multicad_ui');
 Add(Result,'MultiPhysics','Ambientes fisicos','multiphysics/tests/test_environment.lpr','multiphysics/tests/test_environment');
 Add(Result,'MultiPhysics','Dinamica 6DOF','multiphysics/tests/test_rigidbody.lpr','multiphysics/tests/test_rigidbody');
 Add(Result,'MultiPhysics','Flutuacao e empuxo','multiphysics/tests/test_buoyancy.lpr','multiphysics/tests/test_buoyancy');
 Add(Result,'MultiPhysics','Runtime eletromecanico','multiphysics/tests/test_runtime.lpr','multiphysics/tests/test_runtime');
 Add(Result,'MultiPhysics','Grafo de maquina executavel','multiphysics/tests/test_graph_runtime.lpr','multiphysics/tests/test_graph_runtime');
 Add(Result,'MultiPhysics','CNC integrada e telemetria','multiphysics/tests/test_integration_suite.lpr','multiphysics/tests/test_integration_suite');
 Add(Result,'MultiPhysics','Montagem e contrato eletrico unificado','multiphysics/tests/test_unified_merge.lpr','multiphysics/tests/test_unified_merge');
 Add(Result,'MultiPhysics','Modelos eletricos e mecanicos','multiphysics/tests/test_extended_models.lpr','multiphysics/tests/test_extended_models');
 Add(Result,'MultiPhysics','Solver eletrico MNA','multiphysics/tests/test_mna.lpr','multiphysics/tests/test_mna');
 Add(Result,'MultiPhysics','Scheduler multifisico','multiphysics/tests/test_scheduler.lpr','multiphysics/tests/test_scheduler');
 Add(Result,'MultiPhysics','MNA transitorio e nao linear','multiphysics/tests/test_transient_nonlinear.lpr','multiphysics/tests/test_transient_nonlinear');
 Add(Result,'MultiPhysics','Atuadores no scheduler','multiphysics/tests/test_actuator_scheduler.lpr','multiphysics/tests/test_actuator_scheduler');
 Add(Result,'MultiPhysics','Ciclo CNC X=100mm e protecoes','multiphysics/tests/test_cnc_cycle.lpr','multiphysics/tests/test_cnc_cycle');
 Add(Result,'MultiPhysics','CNC XYZ e spindle','multiphysics/tests/test_machine_xyz.lpr','multiphysics/tests/test_machine_xyz');
 Add(Result,'MultiPhysics','Falhas da maquina virtual','multiphysics/tests/test_machine_faults.lpr','multiphysics/tests/test_machine_faults');
 Add(Result,'MultiPhysics','Eletronicos comuns','multiphysics/tests/test_common_electronics.lpr','multiphysics/tests/test_common_electronics');
 Add(Result,'MultiPhysics','Digital e potencia','multiphysics/tests/test_digital_power.lpr','multiphysics/tests/test_digital_power');
 Add(Result,'MultiPhysics','Microcontroladores e perifericos','multiphysics/tests/test_mcu.lpr','multiphysics/tests/test_mcu');
 Add(Result,'MultiPhysics','ESP32 para STEP DIR','multiphysics/tests/test_mcu_stepper.lpr','multiphysics/tests/test_mcu_stepper');
 Add(Result,'MultiPhysics','Dispositivos fisicos','multiphysics/tests/test_physical_devices.lpr','multiphysics/tests/test_physical_devices');
 Add(Result,'MultiPhysics','Biblioteca de materiais','multiphysics/tests/test_materials.lpr','multiphysics/tests/test_materials');
 Add(Result,'MultiPhysics','Energia e quimica','multiphysics/tests/test_energy_chemistry.lpr','multiphysics/tests/test_energy_chemistry');
 Add(Result,'MultiPhysics','Degradacao e falhas','multiphysics/tests/test_degradation_faults.lpr','multiphysics/tests/test_degradation_faults');
 Add(Result,'MultiPhysics','Eletromagnetismo','multiphysics/tests/test_electromagnetics.lpr','multiphysics/tests/test_electromagnetics');
 Add(Result,'MultiPhysics','Mecanica classica','multiphysics/tests/test_mechanics.lpr','multiphysics/tests/test_mechanics');
 Add(Result,'MultiAssembly','Modelo eletromecanico','multiassembly/tests/test_multiassembly.lpr','multiassembly/tests/test_multiassembly');
 Add(Result,'MultiCAM','CAM mecanico','multicam/tests/test_mechanical_cam.lpr','multicam/tests/test_mechanical_cam');Add(Result,'MultiCAM','Setup mecanico','multicam/tests/test_mechanical_setup.lpr','multicam/tests/test_mechanical_setup');Add(Result,'MultiCAM','Simulacao','multicam/tests/test_simulation.lpr','multicam/tests/test_simulation');Add(Result,'MultiCAM','Eletronica virtual','multicam/tests/test_electronics_simulation.lpr','multicam/tests/test_electronics_simulation');Add(Result,'MultiCAM','Pipeline demo','multicam/tests/test_demo_pipeline.lpr','multicam/tests/test_demo_pipeline');
 Add(Result,'MultiSlicer','Layout 3D','multislicer/tests/test_layout3d.lpr','multislicer/tests/test_layout3d');
 Add(Result,'LaserPCB','Job laser','laserpcb/tests/test_job.lpr','laserpcb/tests/test_job');Add(Result,'LaserPCB','Layout','laserpcb/tests/test_layout.lpr','laserpcb/tests/test_layout');Add(Result,'LaserPCB','Alinhamento','laserpcb/tests/test_alignment.lpr','laserpcb/tests/test_alignment');Add(Result,'LaserArt','Calibracao','laserart/tests/test_calibration_matrix.lpr','laserart/tests/test_calibration_matrix');Add(Result,'LaserArt','Saida G-code, SVG e imagem','laserart/tests/test_laserart_output.lpr','laserart/tests/test_laserart_output');
 Add(Result,'LaserPCB','SVG, Gerber, Excellon e CAM','laserpcb/tests/test_pipeline.lpr','laserpcb/tests/test_pipeline');Add(Result,'LaserPCB','Furacao (CNC Router e marcacao)','laserpcb/tests/test_drill.lpr','laserpcb/tests/test_drill');
 Add(Result,'LaserPCB','Interface nativa','laserpcb/tests/test_ui.lpr','laserpcb/tests/test_ui');
 Add(Result,'MakeRouter','Percursos, zero virtual, G-code e simulacao','makerouter/tests/test_makerouter.lpr','makerouter/tests/test_makerouter');Add(Result,'MakeRouter','Interface nativa','makerouter/tests/test_makerouter_ui.lpr','makerouter/tests/test_makerouter_ui');
 Add(Result,'RouterPCB','Isolacao, furacao, recorte, nivelamento e G-code','routerpcb/tests/test_routerpcb.lpr','routerpcb/tests/test_routerpcb');Add(Result,'RouterPCB','Interface nativa','routerpcb/tests/test_routerpcb_ui.lpr','routerpcb/tests/test_routerpcb_ui');
 Add(Result,'MultiSuite','Registro','multisuite/tests/test_registry.lpr','multisuite/tests/test_registry');Add(Result,'MultiSuite','Workspace','multisuite/tests/test_workspace.lpr','multisuite/tests/test_workspace');
 Add(Result,'MultiCAM','advanced mechanical','multicam/tests/test_advanced_mechanical.lpr','multicam/tests/test_advanced_mechanical');
 Add(Result,'MultiCAM','integrated simulator','multicam/tests/test_integrated_simulator.lpr','multicam/tests/test_integrated_simulator');
 Add(Result,'MultiCAM','pcb heightmap','multicam/tests/test_pcb_heightmap.lpr','multicam/tests/test_pcb_heightmap');
 Add(Result,'MultiCAM','pcb outside heightmap','multicam/tests/test_pcb_outside_heightmap.lpr','multicam/tests/test_pcb_outside_heightmap');
 Add(Result,'MultiCAM','pcb segmented heightmap','multicam/tests/test_pcb_segmented_heightmap.lpr','multicam/tests/test_pcb_segmented_heightmap');
 Add(Result,'MultiCAM','profile','multicam/tests/test_profile.lpr','multicam/tests/test_profile');
 Add(Result,'MultiCAM','real physics','multicam/tests/test_real_physics.lpr','multicam/tests/test_real_physics');
 Add(Result,'MultiCAM','simulation session','multicam/tests/test_simulation_session.lpr','multicam/tests/test_simulation_session');
 Add(Result,'MultiSuite','context','multisuite/tests/test_context.lpr','multisuite/tests/test_context');
 Add(Result,'MultiSuite','launcher delivery','multisuite/tests/test_launcher_delivery.lpr','multisuite/tests/test_launcher_delivery');
 Add(Result,'MultiSuite','launcher paths','multisuite/tests/test_launcher_paths.lpr','multisuite/tests/test_launcher_paths');
 Add(Result,'MultiSuite','runner','multisuite/tests/test_runner.lpr','multisuite/tests/test_runner');
 Add(Result,'MultiSuite','workspace validation','multisuite/tests/test_workspace_validation.lpr','multisuite/tests/test_workspace_validation');
 Add(Result,'MultiCNC','gcode trace','tests/test_gcode_trace.lpr','tests/test_gcode_trace');
 Add(Result,'MultiCNC','session','tests/test_session.lpr','tests/test_session');


 Add(Result,'MultiCNC','Controlador: status, streaming, preflight, TCP','tests/test_controller.lpr','tests/test_controller');
 Add(Result,'MultiCNC','Geometria compartilhada e arc fitting','tests/test_shared_geometry.lpr','tests/test_shared_geometry');
 Add(Result,'MultiCAM','HSM, feeds & speeds e pos-processador G2/G3','multicam/tests/test_hsm.lpr','multicam/tests/test_hsm');
 Add(Result,'LaserArt','Raster: dithering, potencia variavel, overscan','laserpcb/tests/test_raster.lpr','laserpcb/tests/test_raster');
 Add(Result,'MultiSlicer','Fatiador moderno: gyroid, adaptativo, Klipper','multislicer/tests/test_modern_slicer.lpr','multislicer/tests/test_modern_slicer');
 Add(Result,'MultiPhysics','MNA Newton-Raphson e integradores','multiphysics/tests/test_newton_ode.lpr','multiphysics/tests/test_newton_ode');
 Add(Result,'MultiCAD','Restricoes, DOF, extrusao, STL/3MF','multicad/tests/test_parametric.lpr','multicad/tests/test_parametric');
 Add(Result,'MultiAssembly','ERC, BOM e configuracao de firmware','multiassembly/tests/test_engineering.lpr','multiassembly/tests/test_engineering');
end;
end.
