unit multisuite_main;
{$mode objfpc}{$H+}
interface
uses Classes,SysUtils,Forms,Controls,StdCtrls,ComCtrls,ExtCtrls,Dialogs,multisuite_types,multisuite_registry,multisuite_launcher,multisuite_workspace;
type TMultiSuiteForm=class(TForm)
 private Registry:TSuiteRegistry;Workspace:TWorkspace;Tools:TListBox;Tree:TTreeView;Flow:TListBox;Info:TLabel;Root:string;procedure OpenTool(Sender:TObject);procedure SelectTool(Sender:TObject);procedure NewDemo(Sender:TObject);procedure RefreshWorkspace;function Button(const S:string;H:TNotifyEvent):TButton;
 public constructor Create(AOwner:TComponent);override;destructor Destroy;override;
 end;
implementation
function TMultiSuiteForm.Button(const S:string;H:TNotifyEvent):TButton;begin Result:=TButton.Create(Self);Result.Parent:=Self;Result.Align:=alTop;Result.Height:=40;Result.Caption:=S;Result.OnClick:=H;end;
constructor TMultiSuiteForm.Create(AOwner:TComponent);var I:Integer;T:TSuiteToolInfo;RightPanel:TPanel;begin inherited;Caption:='MultiSuite - Workspace Unificado de Engenharia e Fabricacao';Width:=1250;Height:=760;Registry:=TSuiteRegistry.Create;Workspace:=TWorkspace.Create;Root:=ExpandFileName(ExtractFilePath(ParamStr(0))+'..'+DirectorySeparator+'..'+DirectorySeparator+'..'+DirectorySeparator);Tree:=TTreeView.Create(Self);Tree.Parent:=Self;Tree.Align:=alLeft;Tree.Width:=330;RightPanel:=TPanel.Create(Self);RightPanel.Parent:=Self;RightPanel.Align:=alRight;RightPanel.Width:=330;Tools:=TListBox.Create(RightPanel);Tools.Parent:=RightPanel;Tools.Align:=alClient;Tools.OnClick:=@SelectTool;for I:=0 to Registry.Count-1 do begin T:=Registry.Tool(I);Tools.Items.AddObject(T.Name,TObject(PtrInt(I)));end;Button('Abrir ferramenta selecionada',@OpenTool).Parent:=RightPanel;Flow:=TListBox.Create(Self);Flow.Parent:=Self;Flow.Align:=alBottom;Flow.Height:=180;Info:=TLabel.Create(Self);Info.Parent:=Self;Info.Align:=alTop;Info.AutoSize:=False;Info.Height:=85;Info.Caption:='Crie ou abra um projeto para iniciar o fluxo de engenharia.';Button('Criar projeto demonstracao',@NewDemo);end;
destructor TMultiSuiteForm.Destroy;begin Workspace.Free;Registry.Free;inherited;end;
procedure TMultiSuiteForm.NewDemo(Sender:TObject);var A:TProjectArtifact;begin Workspace.NewProject('Projeto CNC Integrado',IncludeTrailingPathDelimiter(Root)+'projects'+DirectorySeparator+'cnc_demo');A.Name:='Estrutura mecanica';A.FileName:='cad/estrutura.mcad';A.Kind:=akCAD;A.Tool:=stiMultiCAD;Workspace.AddArtifact(A);A.Name:='Placa controladora';A.FileName:='pcb/controladora.mpcb';A.Kind:=akPCB;A.Tool:=stiMultiPCB;Workspace.AddArtifact(A);A.Name:='Montagem CNC';A.FileName:='assembly/cnc.massembly';A.Kind:=akAssembly;A.Tool:=stiMultiAssembly;Workspace.AddArtifact(A);A.Name:='Usinagem mecanica';A.FileName:='cam/usinagem.mcam';A.Kind:=akCAM;A.Tool:=stiMultiCAM;Workspace.AddArtifact(A);Workspace.SetStage(wsDesign,ssReady);Workspace.SetStage(wsElectronics,ssReady);RefreshWorkspace;end;
procedure TMultiSuiteForm.RefreshWorkspace;var RootNode,N:TTreeNode;I:Integer;A:TProjectArtifact;S:TWorkflowStage;begin Tree.Items.BeginUpdate;try Tree.Items.Clear;RootNode:=Tree.Items.Add(nil,Workspace.Project.Name);N:=Tree.Items.AddChild(RootNode,'Artefatos');for I:=0 to Workspace.ArtifactCount-1 do begin A:=Workspace.Artifact(I);Tree.Items.AddChild(N,ArtifactKindName(A.Kind)+' - '+A.Name+' ['+A.FileName+']');end;N:=Tree.Items.AddChild(RootNode,'Ferramentas');for I:=0 to Registry.Count-1 do Tree.Items.AddChild(N,Registry.Tool(I).Name);RootNode.Expand(True);finally Tree.Items.EndUpdate;end;Flow.Clear;for S:=Low(TWorkflowStage)to High(TWorkflowStage)do Flow.Items.Add(StageName(S)+' : '+StateName(Workspace.Stage(S)));Info.Caption:='Projeto: '+Workspace.Project.Name+LineEnding+'Diretorio: '+Workspace.Project.RootPath+LineEnding+Format('%d artefatos | %d ferramentas disponiveis',[Workspace.ArtifactCount,Registry.Count]);end;
procedure TMultiSuiteForm.SelectTool(Sender:TObject);var I:Integer;T:TSuiteToolInfo;begin I:=Tools.ItemIndex;if I<0 then Exit;I:=PtrInt(Tools.Items.Objects[I]);T:=Registry.Tool(I);Info.Caption:=T.Name+LineEnding+T.Description+LineEnding+'Modulo: '+T.ProjectFile;end;
procedure TMultiSuiteForm.OpenTool(Sender:TObject);var I:Integer;T:TSuiteToolInfo;E:string;begin I:=Tools.ItemIndex;if I<0 then begin ShowMessage('Selecione uma ferramenta.');Exit;end;I:=PtrInt(Tools.Items.Objects[I]);T:=Registry.Tool(I);if not TSuiteLauncher.Launch(T,Root,Workspace.Project.RootPath,E)then ShowMessage(E);end;
end.
