unit multiphysics_main;
{$mode objfpc}{$H+}
interface
uses Classes,SysUtils,Forms,Controls,StdCtrls,ComCtrls,ExtCtrls,multiphysics_types,multiphysics_project,multiphysics_materials,multiphysics_solver,multiphysics_environment,multiphysics_scenario,multiphysics_vector,multiphysics_rigidbody,multiphysics_buoyancy,multiphysics_runtime,multiphysics_runtime_types,multiphysics_graph,multiphysics_graph_runtime,multiphysics_machine_runtime,multiphysics_machine_instruments;
type TMultiPhysicsForm=class(TForm)
 private Machine:TMachineRuntime;P:TPhysicsProject;Graph:TSimulationGraph;GraphRuntime:TGraphRuntime;Runtime:TSimulationRuntime;RuntimeTimer:TTimer;Scenario:TSimulationScenario;Tree:TTreeView;Log:TMemo;Props:TPanel;EnvBox:TComboBox;FlowEdit,AreaEdit,VolumeEdit,CdEdit:TEdit;procedure MachineDemo(Sender:TObject);procedure MachineCommand(Sender:TObject);procedure Demo(Sender:TObject);procedure Analyze(Sender:TObject);procedure FloatTest(Sender:TObject);procedure LoadMachine(Sender:TObject);procedure RuntimeStart(Sender:TObject);procedure RuntimePause(Sender:TObject);procedure RuntimeStop(Sender:TObject);procedure RuntimeTick(Sender:TObject);procedure EnvironmentChanged(Sender:TObject);procedure Estimate(Sender:TObject);procedure RefreshTree;
 public constructor Create(AOwner:TComponent);override;destructor Destroy;override;
 end;
implementation
constructor TMultiPhysicsForm.Create(AOwner:TComponent);var B:TButton;begin inherited;Caption:='MultiPhysics - Simulacao Fisica da Montagem';Width:=1200;Height:=760;P:=TPhysicsProject.Create;Machine:=TMachineRuntime.Create;Graph:=nil;GraphRuntime:=nil;Runtime:=TSimulationRuntime.Create;RuntimeTimer:=TTimer.Create(Self);RuntimeTimer.Enabled:=False;RuntimeTimer.Interval:=20;RuntimeTimer.OnTimer:=@RuntimeTick;Scenario:=MarineScenario;EnvBox:=TComboBox.Create(Self);EnvBox.Parent:=Self;EnvBox.Align:=alTop;EnvBox.Items.Add('Ar');EnvBox.Items.Add('Agua');EnvBox.Items.Add('Vacuo');EnvBox.ItemIndex:=1;EnvBox.OnChange:=@EnvironmentChanged;FlowEdit:=TEdit.Create(Self);FlowEdit.Parent:=Self;FlowEdit.Align:=alTop;FlowEdit.Text:='2';FlowEdit.Hint:='Velocidade do fluido m/s';FlowEdit.ShowHint:=True;AreaEdit:=TEdit.Create(Self);AreaEdit.Parent:=Self;AreaEdit.Align:=alTop;AreaEdit.Text:='1';AreaEdit.Hint:='Area de referencia m2';AreaEdit.ShowHint:=True;VolumeEdit:=TEdit.Create(Self);VolumeEdit.Parent:=Self;VolumeEdit.Align:=alTop;VolumeEdit.Text:='0.1';VolumeEdit.Hint:='Volume deslocado m3';VolumeEdit.ShowHint:=True;CdEdit:=TEdit.Create(Self);CdEdit.Parent:=Self;CdEdit.Align:=alTop;CdEdit.Text:='0.8';CdEdit.Hint:='Coeficiente de arrasto';CdEdit.ShowHint:=True;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='Estimar ambiente / fluido';B.OnClick:=@Estimate;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='Teste preliminar de flutuacao';B.OnClick:=@FloatTest;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='CNC XYZ + SPINDLE';B.OnClick:=@MachineDemo;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='COMANDO X=100 Y=50 Z=20';B.OnClick:=@MachineCommand;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='DESLIGAR SIMULACAO';B.OnClick:=@RuntimeStop;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='PAUSAR SIMULACAO';B.OnClick:=@RuntimePause;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='CARREGAR MAQUINA EXECUTAVEL';B.OnClick:=@LoadMachine;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='LIGAR SIMULACAO';B.OnClick:=@RuntimeStart;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='Carregar demonstracao mecanica/termica';B.OnClick:=@Demo;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='Preparar analise FEM';B.OnClick:=@Analyze;Tree:=TTreeView.Create(Self);Tree.Parent:=Self;Tree.Align:=alLeft;Tree.Width:=340;Log:=TMemo.Create(Self);Log.Parent:=Self;Log.Align:=alClient;Log.ScrollBars:=ssAutoBoth;Log.Lines.Add('MultiPhysics: estrutural + termica + vibracao + contato + arrasto.');end;
destructor TMultiPhysicsForm.Destroy;begin GraphRuntime.Free;Graph.Free;Runtime.Free;Machine.Free;P.Free;inherited;end;
procedure TMultiPhysicsForm.MachineDemo(Sender:TObject);begin Machine.Clear;Machine.AddAxis('X',0,300,80,1.2);Machine.AddAxis('Y',0,200,80,1.2);Machine.AddAxis('Z',0,100,400,1.5);Machine.SetSpindle(12000);Machine.Start;Log.Lines.Add('CNC virtual XYZ energizada; spindle alvo 12000 RPM.');end;
procedure TMultiPhysicsForm.MachineCommand(Sender:TObject);var I:Integer;begin if Machine.AxisCount=0 then MachineDemo(Sender);Machine.CommandAxis('X',100,50);Machine.CommandAxis('Y',50,40);Machine.CommandAxis('Z',20,10);for I:=1 to 5000 do Machine.Step;SampleMachine(Machine,Log.Lines);if Machine.TripReason<>'' then Log.Lines.Add('TRIP: '+Machine.TripReason);end;
procedure TMultiPhysicsForm.LoadMachine(Sender:TObject);var I:Integer;C:TSimComponent;R,N:TTreeNode;begin GraphRuntime.Free;GraphRuntime:=nil;Graph.Free;Graph:=BuildDemoMachine;GraphRuntime:=TGraphRuntime.Create(Graph,Log.Lines);R:=Tree.Items.Add(nil,'Maquina executavel');for I:=0 to Graph.ComponentCount-1 do begin C:=Graph.ComponentAt(I);N:=Tree.Items.AddChild(R,C.ID+' - '+C.Name);Tree.Items.AddChild(N,'Dominio='+IntToStr(Ord(C.Domain)));end;Tree.Items.AddChild(R,'Conexoes: '+IntToStr(Graph.ConnectionCount));Tree.FullExpand;if GraphRuntime.Prepare then Log.Lines.Add('Maquina pronta para energizar.');end;
procedure TMultiPhysicsForm.RuntimeStart(Sender:TObject);begin if Assigned(GraphRuntime) then begin if not GraphRuntime.Prepare then Exit;GraphRuntime.Start;end else Runtime.Start;RuntimeTimer.Enabled:=True;Log.Lines.Add('SIMULACAO ENERGIZADA');end;
procedure TMultiPhysicsForm.RuntimePause(Sender:TObject);begin if Assigned(GraphRuntime) then GraphRuntime.Pause else Runtime.Pause;RuntimeTimer.Enabled:=False;Log.Lines.Add('SIMULACAO PAUSADA');end;
procedure TMultiPhysicsForm.RuntimeStop(Sender:TObject);begin RuntimeTimer.Enabled:=False;if Assigned(GraphRuntime) then GraphRuntime.Stop else Runtime.Stop;Log.Lines.Add('SIMULACAO DESLIGADA');end;
procedure TMultiPhysicsForm.RuntimeTick(Sender:TObject);var S:TSimulationSnapshot;I:Integer;begin if Assigned(GraphRuntime) then begin for I:=1 to 2 do GraphRuntime.Step;S:=GraphRuntime.Snapshot;end else begin for I:=1 to 2 do Runtime.Step;S:=Runtime.Snapshot;end;if (S.Clock.Step mod 20)=0 then Log.Lines.Add(Format('t=%.2fs | V=%.2fV | I=%.2fA | PWM=%.0f%% | vel=%.2f rad/s | torque=%.3f Nm | T=%.1f C',[S.Clock.Time,S.Electrical.BusVoltage,S.Electrical.TotalCurrent,S.Control.PWM*100,S.Mechanical.Velocity,S.Mechanical.Torque,S.Thermal.Temperature]));end;
procedure TMultiPhysicsForm.EnvironmentChanged(Sender:TObject);begin case EnvBox.ItemIndex of 0:Scenario.Environment:=AirEnvironment;1:Scenario.Environment:=WaterEnvironment;2:Scenario.Environment:=VacuumEnvironment;end;Log.Lines.Add('Ambiente: '+Scenario.Environment.Name);end;
procedure TMultiPhysicsForm.Estimate(Sender:TObject);var R:TFluidEstimate;begin Scenario.Environment.FlowX:=StrToFloatDef(FlowEdit.Text,0);Scenario.ReferenceArea:=StrToFloatDef(AreaEdit.Text,0);Scenario.DisplacedVolume:=StrToFloatDef(VolumeEdit.Text,0);Scenario.DragCoefficient:=StrToFloatDef(CdEdit.Text,0);R:=EstimateFluidLoads(Scenario.Environment,Scenario.ReferenceArea,Scenario.DragCoefficient,Scenario.DisplacedVolume);Log.Lines.Add('--- ESTIMATIVA, NAO CFD ---');Log.Lines.Add('Ambiente: '+Scenario.Environment.Name);Log.Lines.Add('Velocidade: '+FloatToStrF(R.Speed,ffFixed,8,3)+' m/s');Log.Lines.Add('Pressao dinamica: '+FloatToStrF(R.DynamicPressure,ffFixed,12,2)+' Pa');Log.Lines.Add('Arrasto estimado: '+FloatToStrF(R.DragForce,ffFixed,12,2)+' N');Log.Lines.Add('Empuxo: '+FloatToStrF(R.BuoyancyForce,ffFixed,12,2)+' N');Log.Lines.Add('Fidelidade: '+FidelityName(Scenario.Fidelity));end;
procedure TMultiPhysicsForm.FloatTest(Sender:TObject);var B:TRigidBodyState;R:TBuoyancyResult;V:Double;begin FillChar(B,SizeOf(B),0);B.Mass:=100;B.CenterOfMass:=V3(0,0,0.20);B.Inertia:=V3(20,50,50);V:=StrToFloatDef(VolumeEdit.Text,0);R:=EvaluateBuoyancy(B,Scenario.Environment,V,V3(0,0,0));Log.Lines.Add('--- FLUTUACAO PRELIMINAR ---');Log.Lines.Add('Massa demonstracao: 100 kg');Log.Lines.Add('Peso: '+FloatToStrF(R.Weight,ffFixed,12,2)+' N');Log.Lines.Add('Empuxo: '+FloatToStrF(R.Buoyancy,ffFixed,12,2)+' N');Log.Lines.Add('Forca vertical liquida: '+FloatToStrF(R.NetVerticalForce,ffFixed,12,2)+' N');Log.Lines.Add('Estado: '+FloatStateName(R.State));Log.Lines.Add('Ainda nao inclui superficie livre/metacentro/geometria submersa.');end;
procedure TMultiPhysicsForm.Demo(Sender:TObject);var A:TPhysicsPart;B:TBoundaryCondition;C:TContact;begin A:=TPhysicsPart.Create;A.ID:='BASE';A.Name:='Base estrutural';A.Material:=Steel;P.AddPart(A);A:=TPhysicsPart.Create;A.ID:='MOTOR';A.Name:='Motor';A.Material:=Aluminum;P.AddPart(A);B.Name:='Fixacao base';B.TargetID:='BASE';B.Kind:=bkFixed;P.AddBC(B);B.Name:='Carga motor';B.TargetID:='MOTOR';B.Kind:=bkForce;B.Z:=-500;P.AddBC(B);B.Name:='Motor quente';B.TargetID:='MOTOR';B.Kind:=bkTemperature;B.Value:=80;P.AddBC(B);C.Name:='Contato motor-base';C.PartA:='MOTOR';C.PartB:='BASE';C.FrictionCoefficient:=0.30;C.ThermalConductance:=1000;P.AddContact(C);P.Settings.Physics:=[pkStructural,pkThermal,pkModal,pkFriction];RefreshTree;end;
procedure TMultiPhysicsForm.RefreshTree;var R,N:TTreeNode;I:Integer;begin Tree.Items.Clear;R:=Tree.Items.Add(nil,'Montagem');for I:=0 to P.PartCount-1 do Tree.Items.AddChild(R,P.Part(I).Name+' | '+P.Part(I).Material.Name);N:=Tree.Items.Add(nil,'Condicoes de contorno');for I:=0 to P.BCCount-1 do Tree.Items.AddChild(N,P.BC(I).Name);N:=Tree.Items.Add(nil,'Contatos');for I:=0 to P.ContactCount-1 do Tree.Items.AddChild(N,P.Contact(I).Name+' | atrito='+FloatToStr(P.Contact(I).FrictionCoefficient));Tree.FullExpand;end;
procedure TMultiPhysicsForm.Analyze(Sender:TObject);var S:TCalculiXSolver;R:TPhysicsResult;begin S:=TCalculiXSolver.Create(GetEnvironmentVariable('CALCULIX_EXE'));try if not S.Solve(P,R,Log.Lines)then Log.Lines.Add('Defina CALCULIX_EXE e implemente/importe a malha antes da solucao numerica.');finally S.Free;end;end;
end.
