unit multiphysics_main;
{$mode objfpc}{$H+}
interface
uses Classes,SysUtils,Forms,Controls,StdCtrls,ComCtrls,ExtCtrls,multiphysics_types,multiphysics_project,multiphysics_materials,multiphysics_solver,multiphysics_environment,multiphysics_scenario;
type TMultiPhysicsForm=class(TForm)
 private P:TPhysicsProject;Scenario:TSimulationScenario;Tree:TTreeView;Log:TMemo;Props:TPanel;EnvBox:TComboBox;FlowEdit,AreaEdit,VolumeEdit,CdEdit:TEdit;procedure Demo(Sender:TObject);procedure Analyze(Sender:TObject);procedure EnvironmentChanged(Sender:TObject);procedure Estimate(Sender:TObject);procedure RefreshTree;
 public constructor Create(AOwner:TComponent);override;destructor Destroy;override;
 end;
implementation
constructor TMultiPhysicsForm.Create(AOwner:TComponent);var B:TButton;begin inherited;Caption:='MultiPhysics - Simulacao Fisica da Montagem';Width:=1200;Height:=760;P:=TPhysicsProject.Create;Scenario:=MarineScenario;EnvBox:=TComboBox.Create(Self);EnvBox.Parent:=Self;EnvBox.Align:=alTop;EnvBox.Items.Add('Ar');EnvBox.Items.Add('Agua');EnvBox.Items.Add('Vacuo');EnvBox.ItemIndex:=1;EnvBox.OnChange:=@EnvironmentChanged;FlowEdit:=TEdit.Create(Self);FlowEdit.Parent:=Self;FlowEdit.Align:=alTop;FlowEdit.Text:='2';FlowEdit.Hint:='Velocidade do fluido m/s';FlowEdit.ShowHint:=True;AreaEdit:=TEdit.Create(Self);AreaEdit.Parent:=Self;AreaEdit.Align:=alTop;AreaEdit.Text:='1';AreaEdit.Hint:='Area de referencia m2';AreaEdit.ShowHint:=True;VolumeEdit:=TEdit.Create(Self);VolumeEdit.Parent:=Self;VolumeEdit.Align:=alTop;VolumeEdit.Text:='0.1';VolumeEdit.Hint:='Volume deslocado m3';VolumeEdit.ShowHint:=True;CdEdit:=TEdit.Create(Self);CdEdit.Parent:=Self;CdEdit.Align:=alTop;CdEdit.Text:='0.8';CdEdit.Hint:='Coeficiente de arrasto';CdEdit.ShowHint:=True;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='Estimar ambiente / fluido';B.OnClick:=@Estimate;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='Carregar demonstracao mecanica/termica';B.OnClick:=@Demo;B:=TButton.Create(Self);B.Parent:=Self;B.Align:=alTop;B.Caption:='Preparar analise FEM';B.OnClick:=@Analyze;Tree:=TTreeView.Create(Self);Tree.Parent:=Self;Tree.Align:=alLeft;Tree.Width:=340;Log:=TMemo.Create(Self);Log.Parent:=Self;Log.Align:=alClient;Log.ScrollBars:=ssAutoBoth;Log.Lines.Add('MultiPhysics: estrutural + termica + vibracao + contato + arrasto.');end;
destructor TMultiPhysicsForm.Destroy;begin P.Free;inherited;end;
procedure TMultiPhysicsForm.EnvironmentChanged(Sender:TObject);begin case EnvBox.ItemIndex of 0:Scenario.Environment:=AirEnvironment;1:Scenario.Environment:=WaterEnvironment;2:Scenario.Environment:=VacuumEnvironment;end;Log.Lines.Add('Ambiente: '+Scenario.Environment.Name);end;
procedure TMultiPhysicsForm.Estimate(Sender:TObject);var R:TFluidEstimate;begin Scenario.Environment.FlowX:=StrToFloatDef(FlowEdit.Text,0);Scenario.ReferenceArea:=StrToFloatDef(AreaEdit.Text,0);Scenario.DisplacedVolume:=StrToFloatDef(VolumeEdit.Text,0);Scenario.DragCoefficient:=StrToFloatDef(CdEdit.Text,0);R:=EstimateFluidLoads(Scenario.Environment,Scenario.ReferenceArea,Scenario.DragCoefficient,Scenario.DisplacedVolume);Log.Lines.Add('--- ESTIMATIVA, NAO CFD ---');Log.Lines.Add('Ambiente: '+Scenario.Environment.Name);Log.Lines.Add('Velocidade: '+FloatToStrF(R.Speed,ffFixed,8,3)+' m/s');Log.Lines.Add('Pressao dinamica: '+FloatToStrF(R.DynamicPressure,ffFixed,12,2)+' Pa');Log.Lines.Add('Arrasto estimado: '+FloatToStrF(R.DragForce,ffFixed,12,2)+' N');Log.Lines.Add('Empuxo: '+FloatToStrF(R.BuoyancyForce,ffFixed,12,2)+' N');Log.Lines.Add('Fidelidade: '+FidelityName(Scenario.Fidelity));end;
procedure TMultiPhysicsForm.Demo(Sender:TObject);var A:TPhysicsPart;B:TBoundaryCondition;C:TContact;begin A:=TPhysicsPart.Create;A.ID:='BASE';A.Name:='Base estrutural';A.Material:=Steel;P.AddPart(A);A:=TPhysicsPart.Create;A.ID:='MOTOR';A.Name:='Motor';A.Material:=Aluminum;P.AddPart(A);B.Name:='Fixacao base';B.TargetID:='BASE';B.Kind:=bkFixed;P.AddBC(B);B.Name:='Carga motor';B.TargetID:='MOTOR';B.Kind:=bkForce;B.Z:=-500;P.AddBC(B);B.Name:='Motor quente';B.TargetID:='MOTOR';B.Kind:=bkTemperature;B.Value:=80;P.AddBC(B);C.Name:='Contato motor-base';C.PartA:='MOTOR';C.PartB:='BASE';C.FrictionCoefficient:=0.30;C.ThermalConductance:=1000;P.AddContact(C);P.Settings.Physics:=[pkStructural,pkThermal,pkModal,pkFriction];RefreshTree;end;
procedure TMultiPhysicsForm.RefreshTree;var R,N:TTreeNode;I:Integer;begin Tree.Items.Clear;R:=Tree.Items.Add(nil,'Montagem');for I:=0 to P.PartCount-1 do Tree.Items.AddChild(R,P.Part(I).Name+' | '+P.Part(I).Material.Name);N:=Tree.Items.Add(nil,'Condicoes de contorno');for I:=0 to P.BCCount-1 do Tree.Items.AddChild(N,P.BC(I).Name);N:=Tree.Items.Add(nil,'Contatos');for I:=0 to P.ContactCount-1 do Tree.Items.AddChild(N,P.Contact(I).Name+' | atrito='+FloatToStr(P.Contact(I).FrictionCoefficient));Tree.FullExpand;end;
procedure TMultiPhysicsForm.Analyze(Sender:TObject);var S:TCalculiXSolver;R:TPhysicsResult;begin S:=TCalculiXSolver.Create(GetEnvironmentVariable('CALCULIX_EXE'));try if not S.Solve(P,R,Log.Lines)then Log.Lines.Add('Defina CALCULIX_EXE e implemente/importe a malha antes da solucao numerica.');finally S.Free;end;end;
end.
