unit multicam_simulator_form;
{$mode objfpc}{$H+}
interface
uses multisuite_numfmt, Classes,SysUtils,Math,Forms,Controls,StdCtrls,ExtCtrls,multicam_types,multicam_job,multicam_setup,multicam_machine_model,multicam_machine_kinematics,multicam_simulation_player,multicam_machine_canvas,multicam_electronics_types,multicam_electronics_model,multicam_electronics_canvas,multicam_simulation_session,multicam_simulation_canvas,multicam_signal_canvas,multicam_demo_job,multicam_gcode;
type TSimulatorForm=class(TForm)
 private J:TCamJob;SetupObj:TMechanicalSetup;Player:TSimulationPlayer;Kin:TMachineKinematics;Electronics:TElectronicsModel;Session:TSimulationSession;View:TMachineCanvas;ElectronicView:TElectronicsCanvas;StockView:TSimulationCanvas;SignalView:TSignalCanvas;Info:TLabel;Timer:TTimer;procedure PlayClick(Sender:TObject);procedure PauseClick(Sender:TObject);procedure StopClick(Sender:TObject);procedure StepClick(Sender:TObject);procedure EStopClick(Sender:TObject);procedure ResetElectronicClick(Sender:TObject);procedure LoadDemoClick(Sender:TObject);procedure ExportDemoClick(Sender:TObject);procedure Tick(Sender:TObject);procedure Changed(Sender:TObject);function Btn(const S:string;H:TNotifyEvent):TButton;
 public constructor Create(AOwner:TComponent);override;destructor Destroy;override;
 end;
implementation
function TSimulatorForm.Btn(const S:string;H:TNotifyEvent):TButton;begin Result:=TButton.Create(Self);Result.Parent:=Self;Result.Align:=alTop;Result.Caption:=S;Result.OnClick:=H;end;
constructor TSimulatorForm.Create(AOwner:TComponent);var M:TMachineModel;EC:TElectronicsConfig;
begin inherited;Caption:='MultiCAM - Simulador Fisico, Mecanico e Eletronico';Width:=1200;Height:=760;J:=TCamJob.Create;SetupObj:=TMechanicalSetup.Create;Player:=TSimulationPlayer.Create;Kin:=TMachineKinematics.Create;Electronics:=TElectronicsModel.Create;Session:=TSimulationSession.Create;SetupObj.Stock.Width:=300;SetupObj.Stock.Height:=200;SetupObj.Stock.Thickness:=20;SetupObj.Stock.TopZ:=0;M.MinX:=0;M.MaxX:=500;M.MinY:=0;M.MaxY:=400;M.MinZ:=-100;M.MaxZ:=100;M.RapidMMMin:=3000;Kin.Configure(M);EC.StepsPerMMX:=80;EC.StepsPerMMY:=80;EC.StepsPerMMZ:=400;EC.MotorSupplyV:=24;EC.LogicSupplyV:=5;EC.MaxMotorCurrentA:=3;Electronics.Configure(EC);ElectronicView:=TElectronicsCanvas.Create(Self);ElectronicView.Parent:=Self;ElectronicView.Align:=alRight;ElectronicView.Width:=430;ElectronicView.SetState(Electronics.State);StockView:=TSimulationCanvas.Create(Self);StockView.Parent:=Self;StockView.Align:=alBottom;StockView.Height:=180;SignalView:=TSignalCanvas.Create(Self);SignalView.Parent:=Self;SignalView.Align:=alBottom;SignalView.Height:=150;View:=TMachineCanvas.Create(Self);View.Parent:=Self;View.Align:=alClient;View.Setup:=SetupObj;View.Machine:=M;Info:=TLabel.Create(Self);Info.Parent:=Self;Info.Align:=alTop;Info.Caption:='Sem job carregado';Btn('Carregar demo Pocket + Furos + Contorno',@LoadDemoClick);Btn('Exportar G-code demo',@ExportDemoClick);Btn('Play',@PlayClick);Btn('Pause',@PauseClick);Btn('Passo',@StepClick);Btn('Stop',@StopClick);Btn('E-STOP',@EStopClick);Btn('Reset eletronica',@ResetElectronicClick);Player.OnChange:=@Changed;Player.Load(J);Session.Configure(J,SetupObj.Stock,Electronics);StockView.HeightMap:=Session.HeightMap;SignalView.Trace:=Session.Trace;Timer:=TTimer.Create(Self);Timer.Interval:=50;Timer.Enabled:=True;Timer.OnTimer:=@Tick;end;
destructor TSimulatorForm.Destroy;begin Session.Free;Electronics.Free;Kin.Free;Player.Free;SetupObj.Free;J.Free;inherited;end;
procedure TSimulatorForm.LoadDemoClick(Sender:TObject);begin Player.Stop;Electronics.Reset;TDemoJobBuilder.Build(J);SetupObj.Stock:=J.Stock;Session.Configure(J,J.Stock,Electronics);StockView.HeightMap:=Session.HeightMap;SignalView.Trace:=Session.Trace;Player.Load(J);Info.Caption:=Format('Demo carregada: %d movimentos',[J.Count]);StockView.Invalidate;SignalView.Invalidate;end;
procedure TSimulatorForm.ExportDemoClick(Sender:TObject);var FN:string;begin if J.Count=0 then TDemoJobBuilder.Build(J);FN:=ExtractFilePath(ParamStr(0))+'multicam_demo.nc';TCamGCode.ExportJob(J,FN);Info.Caption:='G-code exportado: '+FN;end;
procedure TSimulatorForm.PlayClick(Sender:TObject);begin if Electronics.HasFault then begin Info.Caption:='Execucao bloqueada: falha eletronica ativa';Exit;end;Player.Play;end;
procedure TSimulatorForm.PauseClick(Sender:TObject);begin Player.Pause;end;
procedure TSimulatorForm.StopClick(Sender:TObject);begin Player.Stop;end;
procedure TSimulatorForm.StepClick(Sender:TObject);begin if not Electronics.HasFault then Player.Step;end;
procedure TSimulatorForm.EStopClick(Sender:TObject);begin Electronics.SetEStop(True);Player.Pause;ElectronicView.SetState(Electronics.State);Info.Caption:='E-STOP ativo - movimento e spindle bloqueados';end;
procedure TSimulatorForm.ResetElectronicClick(Sender:TObject);begin Player.Stop;Electronics.Reset;Session.Reset;ElectronicView.SetState(Electronics.State);Info.Caption:='Eletronica virtual resetada';end;
procedure TSimulatorForm.Tick(Sender:TObject);var I,N:Integer;begin if Electronics.HasFault then begin Player.Pause;Exit;end;if Player.State<>psPlaying then Exit;N:=Max(1,Round(Player.Speed));for I:=1 to N do if not Player.Step then Break;end;
procedure TSimulatorForm.Changed(Sender:TObject);var P:TCamPoint;M:TPathMove;begin if Player.Index>=0 then begin P:=Player.Position;M:=J.Move(Player.Index);if not Kin.MoveTo(P)then begin Player.Pause;Info.Caption:='Movimento fora dos limites da maquina';Exit;end;Electronics.ApplyMove(P,M.SpindleOn,J.Tool.SpindleRPM);Session.ApplyMove(Player.Index,Timer.Interval/1000);StockView.Invalidate;SignalView.Invalidate;if Electronics.HasFault then Player.Pause;View.SetPose(Kin.Pose);ElectronicView.SetState(Electronics.State);Info.Caption:=Format('Movimento %d/%d  X %.3f Y %.3f Z %.3f  Pulsos X:%d Y:%d Z:%d',[Player.Index+1,J.Count,P.X,P.Y,P.Z,Electronics.State.X.PulseCount,Electronics.State.Y.PulseCount,Electronics.State.Z.PulseCount],InvariantFS);end else Info.Caption:='Pronto';end;
end.
