unit laserpcb_componentsform;
{$mode objfpc}{$H+}{$codepage utf8}
interface
uses Classes,SysUtils,Math,Types,Forms,Controls,StdCtrls,ExtCtrls,Dialogs,Spin,
  Graphics,makepcb_model,makepcb_library,makepcb_gallery,makepcb_fpeditor,
  makepcb_render,laserpcb_project,multisuite_controls,multisuite_icons;
type
 TLPComponentsForm=class(TForm)
 private
  FProject:TLaserPCBProject;FDoc:TMPDocument;FLib:TMPLibrary;FLibraryFile:string;
  Gallery:TMPGallery;Category:TComboBox;Search:TEdit;Items:TListBox;
  PX,PY:TFloatSpinEdit;Angle,Face:TComboBox;RefEdit:TEdit;
  PaintBox:TPaintBox;Renderer:TMPRenderer;Viewport:TMPViewport;
  Pending:TMPFootprint;Selected:Integer;FUpdating,FDragging:Boolean;Info:TLabel;
  function MakeButton(AParent:TWinControl;const AName,AText:string;X,Y,W:Integer;AIcon:TSuiteIconKind;Handler:TNotifyEvent):TSuiteButton;
  procedure LayoutChanged(Sender:TObject);
  procedure RefreshGallery;
  procedure RefreshItems;
  procedure SelectItem(Sender:TObject);
  procedure FilterChanged(Sender:TObject);
  procedure Pick(Sender:TObject;FP:TMPFootprint);
  procedure PaintPreview(Sender:TObject);
  procedure PreviewDown(Sender:TObject;Button:TMouseButton;Shift:TShiftState;X,Y:Integer);
  procedure PreviewMove(Sender:TObject;Shift:TShiftState;X,Y:Integer);
  procedure PreviewUp(Sender:TObject;Button:TMouseButton;Shift:TShiftState;X,Y:Integer);
  procedure PositionChanged(Sender:TObject);
  procedure AddClick(Sender:TObject);
  procedure DeleteClick(Sender:TObject);
  procedure ImportLibraryClick(Sender:TObject);
  procedure OpenSetClick(Sender:TObject);
  procedure SaveSetClick(Sender:TObject);
  procedure NewComponentClick(Sender:TObject);
  procedure ApplyClick(Sender:TObject);
  procedure CancelClick(Sender:TObject);
 public
  constructor CreateFor(AOwner:TComponent;Project:TLaserPCBProject;const LibraryFile:string='');
  destructor Destroy;override;
  procedure LoadSet(const FileName:string);
  property Document:TMPDocument read FDoc;
 end;
implementation
uses laserpcb_components;
function TLPComponentsForm.MakeButton(AParent:TWinControl;const AName,AText:string;X,Y,W:Integer;AIcon:TSuiteIconKind;Handler:TNotifyEvent):TSuiteButton;
begin Result:=TSuiteButton.Create(Self);Result.Parent:=AParent;Result.Name:=AName;
 Result.SetBounds(X,Y,W,34);Result.Caption:=AText;Result.SetLook(sbsSoft,clSuitePrimary,AIcon);Result.OnClick:=Handler;end;
constructor TLPComponentsForm.CreateFor(AOwner:TComponent;Project:TLaserPCBProject;const LibraryFile:string);
var Header:TSuiteHeader;LeftPanel,Right,Footer,Center:TPanel;Scroll:TScrollBox;L:TLabel;
 function LabelAt(Parent:TWinControl;const AText:string;Y:Integer):TLabel;
 begin Result:=TLabel.Create(Self);Result.Parent:=Parent;Result.SetBounds(12,Y,224,20);Result.AutoSize:=False;Result.Caption:=AText;Result.Font.Color:=clSuiteMuted;end;
 function FloatField(const AName,AText:string;Y:Integer):TFloatSpinEdit;
 begin LabelAt(Right,AText,Y);Result:=TFloatSpinEdit.Create(Self);Result.Parent:=Right;
  Result.Name:=AName;Result.SetBounds(12,Y+22,224,28);Result.MinValue:=-100000;Result.MaxValue:=100000;
  Result.DecimalPlaces:=3;Result.Increment:=0.5;Result.OnChange:=@PositionChanged;end;
begin
 inherited CreateNew(AOwner,1);Caption:='LaserPCB - Componentes';Width:=1180;Height:=820;
 Constraints.MinWidth:=1060;Constraints.MinHeight:=760;Position:=poOwnerFormCenter;
 Font.Name:=SUITE_FONT;Font.Size:=10;Color:=clSuiteSurface;Selected:=-1;FUpdating:=True;
 FProject:=Project;FLib:=MakePCBLibrary;FLibraryFile:=LibraryFile;
 if FLibraryFile='' then FLibraryFile:=LPSharedLibraryFile;
 FLib.LoadUserFile(FLibraryFile);
 FDoc:=TMPDocument.Create;FDoc.BoardW:=Project.Width;FDoc.BoardH:=Project.Height;FDoc.DoubleSided:=True;
 if Project.ComponentSetJSON<>'' then LPLoadComponentSet(FDoc,FLib,Project.ComponentSetJSON);
 Renderer:=TMPRenderer.Create;Renderer.Doc:=FDoc;Renderer.ShowRatsnest:=False;
 Header:=TSuiteHeader.Create(Self);Header.Parent:=Self;Header.Align:=alTop;Header.Height:=72;
 Header.Setup('Componentes','Biblioteca compartilhada com o MakePCB / formas para o laser',sikLayers);
 Footer:=TPanel.Create(Self);Footer.Parent:=Self;Footer.Align:=alBottom;Footer.Height:=62;Footer.BevelOuter:=bvNone;
 Info:=TLabel.Create(Self);Info.Parent:=Footer;Info.SetBounds(16,10,Width-370,44);Info.AutoSize:=False;Info.WordWrap:=True;
 Info.Caption:='Escolha na galeria e clique na placa. Arraste para mover ou ajuste X/Y em mm.';
 MakeButton(Footer,'ApplyComponents','Aplicar na placa',Width-340,14,180,sikTests,@ApplyClick).Anchors:=[akTop,akRight];
 MakeButton(Footer,'CancelComponents','Cancelar',Width-148,14,130,sikClose,@CancelClick).Anchors:=[akTop,akRight];

 LeftPanel:=TPanel.Create(Self);LeftPanel.Parent:=Self;LeftPanel.Align:=alLeft;LeftPanel.Width:=284;LeftPanel.BevelOuter:=bvNone;
 LabelAt(LeftPanel,'Galeria de componentes',10);
 Category:=TComboBox.Create(Self);Category.Parent:=LeftPanel;Category.Name:='ComponentCategory';Category.Style:=csDropDownList;
 Category.SetBounds(12,34,260,28);Category.OnChange:=@FilterChanged;
 Search:=TEdit.Create(Self);Search.Parent:=LeftPanel;Search.Name:='ComponentSearch';Search.SetBounds(12,70,260,28);
 Search.Text:='';Search.TextHint:='Buscar componente';Search.OnChange:=@FilterChanged;
 MakeButton(LeftPanel,'NewSharedComponent','Criar componente',12,108,260,sikNew,@NewComponentClick);
 MakeButton(LeftPanel,'EditSharedComponent','Editar / criar copia',12,148,260,sikGear,@NewComponentClick);
 MakeButton(LeftPanel,'ImportComponentLibrary','Importar biblioteca...',12,188,260,sikImport,@ImportLibraryClick);
 Scroll:=TScrollBox.Create(Self);Scroll.Parent:=LeftPanel;Scroll.Align:=alBottom;Scroll.Top:=232;
 Scroll.Anchors:=[akLeft,akTop,akRight,akBottom];Scroll.Align:=alNone;Scroll.SetBounds(0,232,284,LeftPanel.Height-232);
 Scroll.BorderStyle:=bsNone;Scroll.HorzScrollBar.Visible:=False;
 Gallery:=TMPGallery.Create(Self);Gallery.Parent:=Scroll;Gallery.Width:=264;Gallery.Left:=4;Gallery.OnPick:=@Pick;
 Right:=TPanel.Create(Self);Right.Parent:=Self;Right.Align:=alRight;Right.Width:=250;Right.BevelOuter:=bvNone;
 LabelAt(Right,'Componentes da placa',10);
 Items:=TListBox.Create(Self);Items.Parent:=Right;Items.Name:='PlacedComponents';Items.SetBounds(12,36,224,150);Items.OnClick:=@SelectItem;
 LabelAt(Right,'Referencia',194);RefEdit:=TEdit.Create(Self);RefEdit.Parent:=Right;RefEdit.Name:='ComponentRef';RefEdit.SetBounds(12,216,224,28);RefEdit.OnChange:=@PositionChanged;
 PX:=FloatField('ComponentX','Centro X (mm)',252);PY:=FloatField('ComponentY','Centro Y (mm)',310);
 LabelAt(Right,'Rotacao',370);Angle:=TComboBox.Create(Self);Angle.Parent:=Right;Angle.Name:='ComponentRotation';Angle.SetBounds(12,392,104,28);Angle.Style:=csDropDownList;
 Angle.Items.Add('0');Angle.Items.Add('90');Angle.Items.Add('180');Angle.Items.Add('270');Angle.ItemIndex:=0;Angle.OnChange:=@PositionChanged;
 Face:=TComboBox.Create(Self);Face.Parent:=Right;Face.Name:='ComponentFace';Face.SetBounds(124,392,112,28);Face.Style:=csDropDownList;
 Face.Items.Add('Top');Face.Items.Add('Bottom');Face.ItemIndex:=0;Face.OnChange:=@PositionChanged;
 MakeButton(Right,'AddComponent','Adicionar escolhido',12,436,224,sikNew,@AddClick);
 MakeButton(Right,'DeleteComponent','Excluir da placa',12,478,224,sikTrash,@DeleteClick);
 MakeButton(Right,'OpenComponentSet','Abrir conjunto...',12,532,224,sikFolder,@OpenSetClick);
 MakeButton(Right,'SaveComponentSet','Salvar conjunto...',12,574,224,sikSave,@SaveSetClick);
 L:=LabelAt(Right,'Bottom: espelho do componente; a saida segue o espelho da placa.',620);L.Height:=55;L.WordWrap:=True;
 Center:=TPanel.Create(Self);Center.Parent:=Self;Center.Align:=alClient;Center.BevelOuter:=bvNone;
 PaintBox:=TPaintBox.Create(Self);PaintBox.Parent:=Center;PaintBox.Align:=alClient;
 PaintBox.OnPaint:=@PaintPreview;PaintBox.OnMouseDown:=@PreviewDown;PaintBox.OnMouseMove:=@PreviewMove;PaintBox.OnMouseUp:=@PreviewUp;
 RefreshGallery;RefreshItems;FUpdating:=False;
 PX.Value:=Project.Width/2;PY.Value:=Project.Height/2;OnResize:=@LayoutChanged;OnShow:=@LayoutChanged;
end;
procedure TLPComponentsForm.LayoutChanged(Sender:TObject);
var B:TSuiteButton;
begin
 B:=TSuiteButton(FindComponent('ApplyComponents'));
 if B<>nil then begin B.Parent.Width:=ClientWidth;B.SetBounds(ClientWidth-340,14,180,34);end;
 B:=TSuiteButton(FindComponent('CancelComponents'));if B<>nil then B.SetBounds(ClientWidth-148,14,130,34);
 if Info<>nil then Info.Width:=Max(100,ClientWidth-370);
end;
destructor TLPComponentsForm.Destroy;
begin Renderer.Free;FDoc.Free;inherited;end;
procedure TLPComponentsForm.RefreshGallery;
var I:Integer;
begin
 Category.Items.Clear;Category.Items.Add('Todos');for I:=0 to FLib.Categories.Count-1 do Category.Items.Add(FLib.Categories[I]);
 Category.ItemIndex:=0;Gallery.Lib:=FLib;Gallery.Reload;
end;
procedure TLPComponentsForm.FilterChanged(Sender:TObject);
begin if Category.ItemIndex<=0 then Gallery.Category:='' else Gallery.Category:=Category.Text;Gallery.Filter:=Search.Text;end;
procedure TLPComponentsForm.RefreshItems;
var I:Integer;
begin Items.Items.Clear;for I:=0 to FDoc.ComponentCount-1 do Items.Items.Add(FDoc.Component(I).Ref+' | '+FDoc.Component(I).Footprint.Name);
 if Selected>=FDoc.ComponentCount then Selected:=FDoc.ComponentCount-1;Items.ItemIndex:=Selected;PaintBox.Invalidate;end;
procedure TLPComponentsForm.SelectItem(Sender:TObject);
var C:TMPComponent;
begin Selected:=Items.ItemIndex;if Selected<0 then Exit;Pending:=nil;C:=FDoc.Component(Selected);FUpdating:=True;
 try PX.Value:=C.X;PY.Value:=C.Y;Angle.ItemIndex:=((C.Rotation mod 360)+360)mod 360 div 90;Face.ItemIndex:=Ord(C.Flipped);RefEdit.Text:=C.Ref;
 finally FUpdating:=False;end;PaintBox.Invalidate;end;
procedure TLPComponentsForm.Pick(Sender:TObject;FP:TMPFootprint);
begin Pending:=FP;Selected:=-1;Items.ItemIndex:=-1;Info.Caption:='Selecionado: '+FP.Name+'. Clique na placa ou em Adicionar escolhido.';PaintBox.Invalidate;end;
procedure TLPComponentsForm.PaintPreview(Sender:TObject);
begin
 Viewport.Scale:=Max(0.001,Min((PaintBox.Width-48)/Max(1,FDoc.BoardW),(PaintBox.Height-48)/Max(1,FDoc.BoardH)));
 Viewport.OX:=(PaintBox.Width-FDoc.BoardW*Viewport.Scale)/2;
 Viewport.OY:=(PaintBox.Height+FDoc.BoardH*Viewport.Scale)/2;
 Renderer.SelKind:=selComponent;Renderer.SelIndex:=Selected;Renderer.Paint(PaintBox.Canvas,Viewport,PaintBox.ClientRect);
end;
procedure TLPComponentsForm.PreviewDown(Sender:TObject;Button:TMouseButton;Shift:TShiftState;X,Y:Integer);
var Q:TMPPoint;I:Integer;B:TMPRect;
begin
 if Button<>mbLeft then Exit;Q:=MPToBoard(Viewport,X,Y);
 if Pending<>nil then begin FUpdating:=True;try PX.Value:=Q.X;PY.Value:=Q.Y;finally FUpdating:=False;end;AddClick(nil);Exit;end;
 for I:=FDoc.ComponentCount-1 downto 0 do begin B:=FDoc.Component(I).Bounds;
  if B.Valid and(Q.X>=B.MinX)and(Q.X<=B.MaxX)and(Q.Y>=B.MinY)and(Q.Y<=B.MaxY) then begin Items.ItemIndex:=I;SelectItem(nil);FDragging:=True;Exit;end;end;
end;
procedure TLPComponentsForm.PreviewMove(Sender:TObject;Shift:TShiftState;X,Y:Integer);
var Q:TMPPoint;
begin if not FDragging or not(ssLeft in Shift) or(Selected<0) then Exit;Q:=MPToBoard(Viewport,X,Y);
 FUpdating:=True;try PX.Value:=Round(Q.X*2)/2;PY.Value:=Round(Q.Y*2)/2;finally FUpdating:=False;end;PositionChanged(nil);end;
procedure TLPComponentsForm.PreviewUp(Sender:TObject;Button:TMouseButton;Shift:TShiftState;X,Y:Integer);
begin FDragging:=False;end;
procedure TLPComponentsForm.PositionChanged(Sender:TObject);
var C:TMPComponent;
begin if FUpdating or(Selected<0) then Exit;C:=FDoc.Component(Selected);
 C.X:=PX.Value;C.Y:=PY.Value;C.Rotation:=Angle.ItemIndex*90;C.Flipped:=Face.ItemIndex=1;
 if Trim(RefEdit.Text)<>'' then C.Ref:=Trim(RefEdit.Text);FDoc.Changed;RefreshItems;end;
procedure TLPComponentsForm.AddClick(Sender:TObject);
var C:TMPComponent;
begin if Pending=nil then begin Info.Caption:='Escolha primeiro um componente na galeria.';Exit;end;
 C:=FDoc.AddComponent(Pending,PX.Value,PY.Value);C.Rotation:=Angle.ItemIndex*90;C.Flipped:=Face.ItemIndex=1;
 Selected:=FDoc.ComponentCount-1;Pending:=nil;RefreshItems;SelectItem(nil);end;
procedure TLPComponentsForm.DeleteClick(Sender:TObject);
begin if Selected<0 then Exit;FDoc.DeleteComponent(Selected);RefreshItems;SelectItem(nil);end;
procedure TLPComponentsForm.ImportLibraryClick(Sender:TObject);
var D:TOpenDialog;N:Integer;
begin D:=TOpenDialog.Create(Self);try D.Filter:='Biblioteca MakePCB (*.json)|*.json';if not D.Execute then Exit;
 try FLib.LoadUserFile(FLibraryFile);N:=LPImportComponentLibrary(FLib,D.FileName);FLib.SaveUserFile(FLibraryFile);
  Pending:=nil;RefreshGallery;Info.Caption:=IntToStr(N)+' componentes importados na biblioteca compartilhada.';
 except on E:Exception do Info.Caption:=E.Message;end;
 finally D.Free;end;end;
procedure TLPComponentsForm.LoadSet(const FileName:string);
var S:TStringList;
begin S:=TStringList.Create;try S.LoadFromFile(FileName);LPLoadComponentSet(FDoc,FLib,S.Text);
 FDoc.BoardW:=FProject.Width;FDoc.BoardH:=FProject.Height;FDoc.DoubleSided:=True;
 Selected:=-1;Pending:=nil;RefreshItems;Info.Caption:='Conjunto aberto. Confira as posicoes e aplique na placa.';
 finally S.Free;end;end;
procedure TLPComponentsForm.OpenSetClick(Sender:TObject);
var D:TOpenDialog;
begin D:=TOpenDialog.Create(Self);try D.Filter:='Conjunto / projeto MakePCB (*.mpcb)|*.mpcb|JSON|*.json';if D.Execute then
 try LoadSet(D.FileName);except on E:Exception do Info.Caption:=E.Message;end;finally D.Free;end;end;
procedure TLPComponentsForm.SaveSetClick(Sender:TObject);
var D:TSaveDialog;
begin D:=TSaveDialog.Create(Self);try D.Filter:='Conjunto MakePCB (*.mpcb)|*.mpcb';D.DefaultExt:='mpcb';D.Options:=D.Options+[ofOverwritePrompt];
 if D.Execute then try FDoc.SaveToFile(D.FileName);Info.Caption:='Conjunto salvo: '+D.FileName;
 except on E:Exception do Info.Caption:=E.Message;end;finally D.Free;end;end;
procedure TLPComponentsForm.NewComponentClick(Sender:TObject);
var Ed:TMPFootprintEditor;FP,Template:TMPFootprint;
begin
 Template:=nil;if(Sender<>nil)and(TComponent(Sender).Name='EditSharedComponent') then Template:=Gallery.SelectedFootprint;
 if (Sender<>nil)and(TComponent(Sender).Name='EditSharedComponent')and(Template=nil) then begin Info.Caption:='Escolha um componente para editar.';Exit;end;
 Ed:=TMPFootprintEditor.CreateFor(Self,Template);FP:=nil;
 try FP:=Ed.Execute;finally Ed.Free;end;if FP=nil then Exit;
 try FLib.LoadUserFile(FLibraryFile);FLib.AddUser(FP);FP:=nil;FLib.SaveUserFile(FLibraryFile);Pending:=nil;RefreshGallery;
 Info.Caption:='Componente salvo na biblioteca compartilhada com o MakePCB.';
 except on E:Exception do begin FP.Free;Info.Caption:=E.Message;end;end;
end;
procedure TLPComponentsForm.CancelClick(Sender:TObject);
begin ModalResult:=mrCancel;end;
procedure TLPComponentsForm.ApplyClick(Sender:TObject);
begin try LPApplyComponents(FDoc,FProject);ModalResult:=mrOK;except on E:Exception do Info.Caption:=E.Message;end;end;
end.
