unit multiphysics_materials;
{$mode objfpc}{$H+}
interface
uses multiphysics_types;
function Steel:TMaterial;function Aluminum:TMaterial;function ABSPlastic:TMaterial;
function Iron:TMaterial;function PLAPlastic:TMaterial;function Acrylic:TMaterial;function Glass:TMaterial;
function Gold:TMaterial;function Silver:TMaterial;function Copper:TMaterial;function Lead:TMaterial;
function StainlessSteel304:TMaterial;function Brass:TMaterial;function Bronze:TMaterial;function Titanium:TMaterial;
function PETGPlastic:TMaterial;function Nylon:TMaterial;function PVC:TMaterial;function PTFE:TMaterial;
function SiliconeRubber:TMaterial;function NaturalRubber:TMaterial;
function FR4:TMaterial;function Silicon:TMaterial;function AluminaCeramic:TMaterial;function WoodGeneric:TMaterial;
implementation
function Steel:TMaterial;begin Result.Name:='Aco carbono';Result.Density:=7850;Result.YoungModulus:=200e9;Result.Poisson:=0.30;Result.ThermalConductivity:=50;Result.SpecificHeat:=470;Result.ThermalExpansion:=12e-6;Result.YieldStrength:=250e6;Result.ElectricalResistivity:=1.43e-7;end;
function Aluminum:TMaterial;begin Result.Name:='Aluminio';Result.Density:=2700;Result.YoungModulus:=69e9;Result.Poisson:=0.33;Result.ThermalConductivity:=205;Result.SpecificHeat:=900;Result.ThermalExpansion:=23e-6;Result.YieldStrength:=150e6;Result.ElectricalResistivity:=2.82e-8;end;
function ABSPlastic:TMaterial;begin Result.Name:='ABS';Result.Density:=1040;Result.YoungModulus:=2.1e9;Result.Poisson:=0.35;Result.ThermalConductivity:=0.18;Result.SpecificHeat:=1300;Result.ThermalExpansion:=90e-6;Result.YieldStrength:=40e6;Result.ElectricalResistivity:=1e14;end;
function Iron:TMaterial;begin Result.Name:='Ferro puro';Result.Density:=7874;Result.YoungModulus:=211e9;Result.Poisson:=0.29;Result.ThermalConductivity:=80.4;Result.SpecificHeat:=449;Result.ThermalExpansion:=11.8e-6;Result.YieldStrength:=50e6;Result.ElectricalResistivity:=9.71e-8;end;
function PLAPlastic:TMaterial;begin Result.Name:='PLA';Result.Density:=1240;Result.YoungModulus:=3.5e9;Result.Poisson:=0.36;Result.ThermalConductivity:=0.13;Result.SpecificHeat:=1800;Result.ThermalExpansion:=68e-6;Result.YieldStrength:=60e6;Result.ElectricalResistivity:=1e14;end;
function Acrylic:TMaterial;begin Result.Name:='Acrilico PMMA';Result.Density:=1180;Result.YoungModulus:=3.2e9;Result.Poisson:=0.35;Result.ThermalConductivity:=0.19;Result.SpecificHeat:=1470;Result.ThermalExpansion:=70e-6;Result.YieldStrength:=65e6;Result.ElectricalResistivity:=1e13;end;
function Glass:TMaterial;begin Result.Name:='Vidro soda-cal generico';Result.Density:=2500;Result.YoungModulus:=70e9;Result.Poisson:=0.22;Result.ThermalConductivity:=1.0;Result.SpecificHeat:=840;Result.ThermalExpansion:=9e-6;Result.YieldStrength:=33e6;Result.ElectricalResistivity:=1e10;end;
function Gold:TMaterial;begin Result.Name:='Ouro';Result.Density:=19320;Result.YoungModulus:=79e9;Result.Poisson:=0.44;Result.ThermalConductivity:=318;Result.SpecificHeat:=129;Result.ThermalExpansion:=14.2e-6;Result.YieldStrength:=100e6;Result.ElectricalResistivity:=2.44e-8;end;
function Silver:TMaterial;begin Result.Name:='Prata';Result.Density:=10490;Result.YoungModulus:=83e9;Result.Poisson:=0.37;Result.ThermalConductivity:=429;Result.SpecificHeat:=235;Result.ThermalExpansion:=18.9e-6;Result.YieldStrength:=55e6;Result.ElectricalResistivity:=1.59e-8;end;
function Copper:TMaterial;begin Result.Name:='Cobre';Result.Density:=8960;Result.YoungModulus:=110e9;Result.Poisson:=0.34;Result.ThermalConductivity:=401;Result.SpecificHeat:=385;Result.ThermalExpansion:=16.5e-6;Result.YieldStrength:=70e6;Result.ElectricalResistivity:=1.68e-8;end;
function Lead:TMaterial;begin Result.Name:='Chumbo';Result.Density:=11340;Result.YoungModulus:=16e9;Result.Poisson:=0.44;Result.ThermalConductivity:=35.3;Result.SpecificHeat:=128;Result.ThermalExpansion:=28.9e-6;Result.YieldStrength:=12e6;Result.ElectricalResistivity:=2.2e-7;end;
function StainlessSteel304:TMaterial;begin Result:=Steel;Result.Name:='Aco inox 304';Result.Density:=8000;Result.YoungModulus:=193e9;Result.ThermalConductivity:=16.2;Result.SpecificHeat:=500;Result.ThermalExpansion:=17.2e-6;Result.YieldStrength:=215e6;Result.ElectricalResistivity:=7.2e-7;end;
function Brass:TMaterial;begin Result:=Copper;Result.Name:='Latao';Result.Density:=8500;Result.YoungModulus:=100e9;Result.Poisson:=0.34;Result.ThermalConductivity:=109;Result.SpecificHeat:=380;Result.ThermalExpansion:=20e-6;Result.YieldStrength:=200e6;Result.ElectricalResistivity:=6.5e-8;end;
function Bronze:TMaterial;begin Result:=Copper;Result.Name:='Bronze';Result.Density:=8800;Result.YoungModulus:=110e9;Result.ThermalConductivity:=60;Result.SpecificHeat:=377;Result.ThermalExpansion:=18e-6;Result.YieldStrength:=200e6;Result.ElectricalResistivity:=8.5e-8;end;
function Titanium:TMaterial;begin Result:=Steel;Result.Name:='Titanio';Result.Density:=4500;Result.YoungModulus:=116e9;Result.Poisson:=0.34;Result.ThermalConductivity:=21.9;Result.SpecificHeat:=523;Result.ThermalExpansion:=8.6e-6;Result.YieldStrength:=275e6;Result.ElectricalResistivity:=4.2e-7;end;
function PETGPlastic:TMaterial;begin Result:=PLAPlastic;Result.Name:='PETG';Result.Density:=1270;Result.YoungModulus:=2.1e9;Result.ThermalConductivity:=0.2;Result.SpecificHeat:=1200;Result.YieldStrength:=50e6;Result.ElectricalResistivity:=1e14;end;
function Nylon:TMaterial;begin Result:=ABSPlastic;Result.Name:='Nylon PA';Result.Density:=1140;Result.YoungModulus:=2.5e9;Result.ThermalConductivity:=0.25;Result.SpecificHeat:=1700;Result.YieldStrength:=70e6;Result.ElectricalResistivity:=1e12;end;
function PVC:TMaterial;begin Result:=ABSPlastic;Result.Name:='PVC rigido';Result.Density:=1400;Result.YoungModulus:=3e9;Result.ThermalConductivity:=0.19;Result.SpecificHeat:=900;Result.YieldStrength:=50e6;Result.ElectricalResistivity:=1e14;end;
function PTFE:TMaterial;begin Result:=ABSPlastic;Result.Name:='PTFE / Teflon';Result.Density:=2200;Result.YoungModulus:=0.5e9;Result.Poisson:=0.46;Result.ThermalConductivity:=0.25;Result.SpecificHeat:=1000;Result.ThermalExpansion:=120e-6;Result.YieldStrength:=23e6;Result.ElectricalResistivity:=1e18;end;
function SiliconeRubber:TMaterial;begin Result:=ABSPlastic;Result.Name:='Borracha de silicone';Result.Density:=1100;Result.YoungModulus:=5e6;Result.Poisson:=0.49;Result.ThermalConductivity:=0.2;Result.SpecificHeat:=1500;Result.YieldStrength:=5e6;Result.ElectricalResistivity:=1e14;end;
function NaturalRubber:TMaterial;begin Result:=SiliconeRubber;Result.Name:='Borracha natural';Result.Density:=930;Result.YoungModulus:=3e6;Result.ThermalConductivity:=0.13;Result.SpecificHeat:=1900;end;
function FR4:TMaterial;begin Result:=ABSPlastic;Result.Name:='FR-4 PCB';Result.Density:=1850;Result.YoungModulus:=22e9;Result.Poisson:=0.14;Result.ThermalConductivity:=0.3;Result.SpecificHeat:=1200;Result.ThermalExpansion:=14e-6;Result.YieldStrength:=300e6;Result.ElectricalResistivity:=1e14;end;
function Silicon:TMaterial;begin Result:=Glass;Result.Name:='Silicio';Result.Density:=2330;Result.YoungModulus:=130e9;Result.Poisson:=0.28;Result.ThermalConductivity:=148;Result.SpecificHeat:=700;Result.ThermalExpansion:=2.6e-6;Result.YieldStrength:=7000e6;Result.ElectricalResistivity:=2300;end;
function AluminaCeramic:TMaterial;begin Result:=Glass;Result.Name:='Ceramica alumina';Result.Density:=3900;Result.YoungModulus:=370e9;Result.Poisson:=0.22;Result.ThermalConductivity:=30;Result.SpecificHeat:=880;Result.ThermalExpansion:=8e-6;Result.YieldStrength:=300e6;Result.ElectricalResistivity:=1e12;end;
function WoodGeneric:TMaterial;begin Result:=ABSPlastic;Result.Name:='Madeira generica';Result.Density:=650;Result.YoungModulus:=10e9;Result.Poisson:=0.35;Result.ThermalConductivity:=0.12;Result.SpecificHeat:=1700;Result.ThermalExpansion:=5e-6;Result.YieldStrength:=40e6;Result.ElectricalResistivity:=1e10;end;
end.
